name: Create Release and Compress Files

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment
        run: sudo apt-get install -y zip jq

      - name: Extract version from manifest
        id: get_version
        run: |
          VERSION=$(jq -r '.version' manifest.json)
          echo "version=$VERSION" >> $GITHUB_ENV

      - name: Compress files
        run: |
          zip -r "MINECRAFT_RESURGENCE_${{ env.version }}.zip" . -x ".git*" ".github/*" "*.gitignore"
        
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          token: ${{ secrets.AUTH_TOKEN }}  # Correctly pass the token as 'token'
          tag_name: "v${{ env.version }}"
          release_name: "MINECRAFT_RESURGENCE_${{ env.version }}"
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          token: ${{ secrets.AUTH_TOKEN }}  # Correctly pass the token as 'token'
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "./MINECRAFT_RESURGENCE_${{ env.version }}.zip"
          asset_name: "MINECRAFT_RESURGENCE_${{ env.version }}.zip"
          asset_content_type: application/zip
